### ISSUE TITLE
Cost policies without Optima fail 

### ISSUE THREAD

**Issue by ryanoleary** [flexera/policy_templates#310]
### Policy Template Name
Low Service Usage, but may apply to others as well

### Issue Type
Bug?

I don't have any costs hooked up to this Org, so I assume that's why I'm getting this error message. But it isn't clear.

### Policy Template version (Bug Only)
1.2

### Error Messages (Bug Only)
Summary:
  failed to retrieve datasource data
Detail:
  failed to parse response JSON
  POST https://optima.rightscale.com/bill-analysis/orgs/2670/costs/aggregated
  unexpected end of JSON input
Location:
  datasource "ds_format_costs"
    script "js_format_costs"
      argument "new_bc_costs"
        datasource "ds_new_bc_costs"

**Comment by rshade** [comment]
We fixed this.
