### ISSUE TITLE
Policy failed to terminate instances enhancement.

### ISSUE THREAD

**Issue by CoryShepherd** [flexera/policy_templates#429]
### Policy Template Name
Azure Disallowed Regions

### Issue Type
Feature Request

### Use Case (Feature Request -or- New Policy Template Request Only)
Currently if the policy is unable to delete an out of compliance instance it will attempt to do so and skip it with no indication that it was unable to terminate it.  Looking for indication that it failed to terminate the instances.

**Comment by cdwilhelm** [comment]
Tracking in POL-177
