### ISSUE TITLE
Have Azure Subscription Access policy trigger incident even if the list doesn't change

### ISSUE THREAD

**Issue by tjohnson1228** [flexera/policy_templates#504]
### Policy Template Name
Azure Subscription Access

### Issue Type
Feature Request

### Use Case (Feature Request -or- New Policy Template Request Only)
From the customer, we have the Azure Subscription Access policy applied to many organizations. We have a requirement from one of our customers to audit exactly what this policy audits. The problem we’re running into is we need a report generated each week from this policy but this policy looks to only generate a report the first time this governance policy is applied, but only again if a new owner/contributor is added. Is it possible to have this policy changed, to email every week no matter if there is a change or not?

**Comment by cdwilhelm** [comment]
The requested behavior isn't how a policy is expected to work.  Instead the customer can create their own version to create the desired behavior.
To get the designed behavior they need to force the the datasource to change every time, they can be done with a timestamp or other value.
